### NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. 



### step 1 : import numpy

In [1]:
import numpy as np

For understanding concept of numpy we create simple list and change this list into Array using np.array() function

In [2]:
ls = [10,33,54, 7.7, "yasmeen", 31]
ls

[10, 33, 54, 7.7, 'yasmeen', 31]

In [3]:
arr = np.array(ls)
arr

array(['10', '33', '54', '7.7', 'yasmeen', '31'], dtype='<U32')

type(arrr) -> used for check the type of array 

In [4]:
type(arr) 

numpy.ndarray

In numpy we can perform Arithmetic operation easily on an array


In [5]:
arr1 = np.array([1,2,3,4,5])
result = arr1+1
result

array([2, 3, 4, 5, 6])

#### arr.ndim ->  this function used for find no. of dimension   [[],[],[]] -> multi dimension array
#### array is collection of similar type of data items store in contigeous memory allocation
#### in python array is flexible insert any type of data but its effect on array type
#### array have fixed size 

#### arr.dtype -> This function used for check type of array

In [6]:
arr.dtype   

dtype('<U32')

#### address of array = first item address + (data_type size + position of item)

In [7]:
arr1 = (43 , 33, 44 ,77 ,78 ,90)
arr1[2]  

44

#### In NumPy, we can perform a wide variety of operations on arrays, including arithmetic operations, array manipulation, aggregation, statistical operations, and more. Here's an overview of some common operations you can perform on NumPy arrays:



In [8]:
# Arithmetic Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_add = arr1 + arr2  
result_add




array([5, 7, 9])

#### Aggregation Operations
#### We can aggregate data in NumPy arrays using functions like np.sum(), np.mean(), np.min(), np.max(), np.median(), np.std(), etc. These functions allow you to compute statistics across the entire array or along specific axes:



In [9]:
arr_1 = np.array([2,3,4,5,6,7])
total = np.sum(arr_1)  
average = np.mean(arr_1)  
max_value = np.max(arr_1)  
min_value = np.min(arr_1)  
median_value = np.median(arr_1)  
std_deviation = np.std(arr_1)  
print("Array sum is :" , total)
print("Array average is :" , average)
print("Array max_value is :" , max_value)
print("Array min_value is :" , min_value)
print("Array median_value is :" , median_value)
print("Array std_deviation is :" , std_deviation)

Array sum is : 27
Array average is : 4.5
Array max_value is : 7
Array min_value is : 2
Array median_value is : 4.5
Array std_deviation is : 1.707825127659933


In [10]:
ls = [ 44, 45 , 65 ,56, 34, 97, 43, 22]
arr = np.array(ls)
arr

array([44, 45, 65, 56, 34, 97, 43, 22])

In [11]:
arr[2:5:2]   

array([65, 34])

#### The ndim attribute in NumPy is used to determine the number of dimensions (or axes) of a NumPy array. 



In [12]:
arr.ndim

1

#####  arr.size -> len(arr)   example of polymorphism

In [13]:
len(arr)  

8

##### using python print all number from array that is greater than 50

In [14]:
for i in arr:
    if i>50:
        print(i)   
    

65
56
97


##### using numpy print all number from array that is greater than 50

In [15]:
arr[arr<50]    

array([44, 45, 34, 43, 22])

#### The `shape` attribute of a NumPy array returns a tuple that represents the dimensions of the array. For example, for a 2-dimensional array with 3 rows and 4 columns, `arr.shape` would return `(3, 4)`, indicating the size of each dimension of the array.

In [16]:
arr.shape   

(8,)

#### Function: np.arange() is a function in NumPy that creates an array containing evenly spaced values within a given interval.

#### Parameters: It takes three parameters: start, stop, and step. However, when called with a single argument (np.arange(50)), it assumes the argument as stop, and defaults start to 0 and step to 1.



In [17]:
arr2 = np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

##### `np.ones(10)` is a NumPy function call that creates an array containing 10 floating-point numbers, each initialized to the value 1.

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### np.ones((10,5))  ->  2D array --> 10 row and 5 column for any demension array used np.ones

In [19]:
np.ones((10,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### `np.zeros(10)` is a NumPy function call that creates an array containing n floating-point numbers, each initialized to the value 0.

In [20]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##### np.linspace(1, 8, 5) generates an array of 5 evenly spaced numbers from 1 to 8, inclusive.

In [21]:
np.linspace(1,8,5) 

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [22]:
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

##### import random enables the use of Python's built-in module for random number generation and other related operations, offering flexibility and convenience in generating randomness within our programs.





In [23]:
import random 

 ##### Gives random value between 1-10

In [24]:
random.randint(1,10)  

5

##### random.random() --->  return value between 0-1 randomly

In [25]:
random.random()

0.9525225891411806

In [26]:
ls = ['student1' , 'student1' , 'student3' , 'student4']
ls

['student1', 'student1', 'student3', 'student4']

##### `random.choice(ls)` is a function call from the `random` module in Python that selects a random element from the non-empty sequence `ls`.

In [27]:
random.choice(ls)

'student3'

##### `random.choices(ls, k=3)` is a function call from the `random` module in Python that returns a list of `k` random elements with replacement from the sequence `ls`.

In [28]:
random.choices(ls, k= 3)

['student4', 'student4', 'student1']

##### `random.shuffle(ls)` is a function call from the `random` module in Python that shuffles the elements of the list `ls` in place, altering its order randomly.

In [29]:
random.shuffle(ls)
ls

['student1', 'student3', 'student4', 'student1']

##### `arr = np.random.randint(1, 50, 10)` creates a NumPy array `arr` with 10 integers randomly chosen from the interval [1, 50]. Each integer is independently and uniformly selected from this range.

In [30]:
arr= np.random.randint(1,50,10) 
arr

array([ 8, 18,  7, 14, 28, 29, 45, 25,  7, 16], dtype=int32)

In [31]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

##### `arr.reshape(12, 5)` reshapes the NumPy array `arr` into a new shape of (12, 5), meaning it arranges the elements of `arr` into 12 rows and 5 columns while maintaining the total number of elements.

In [32]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
arr = np.random.randint(5,50,100)
arr

array([21,  5, 10, 44, 43, 29, 17, 19, 15, 39, 48, 33, 21, 14, 41,  9, 18,
       28, 29, 31, 19, 19,  8, 29, 48, 46, 27, 45, 27, 29,  5, 36, 41, 48,
       16,  9, 36, 27, 49, 12,  9, 41, 22, 19, 39, 31, 43, 15, 15, 41, 28,
       17, 42, 21, 15,  5, 34, 28, 36, 45, 32, 42,  9, 44, 46, 34, 20, 49,
       22, 10, 20,  5, 32, 42,  8, 16,  7, 49, 10,  7, 23, 37, 30, 39,  5,
       30, 39,  6, 32,  6, 39, 24,  6, 18,  5, 27,  6,  8, 12, 28],
      dtype=int32)

##### arr = np.random.randint(5, 50, (4, 3)) creates a NumPy array arr with shape (4, 3) where each element is a random integer chosen from the interval [5, 50]

In [34]:
arr= np.random.randint(5,50,(4,3))   
arr

array([[26, 28, 47],
       [32,  5, 38],
       [43, 27, 12],
       [39, 25, 44]], dtype=int32)

##### `np.transpose(arr)` returns the transpose of the NumPy array `arr`, effectively swapping its rows and columns.

In [35]:
np.transpose(arr)

array([[26, 32, 43, 39],
       [28,  5, 27, 25],
       [47, 38, 12, 44]], dtype=int32)

##### `arr.ravel()` returns a flattened version of the NumPy array `arr`, i.e., it collapses the array into a one-dimensional array by concatenating all elements in row-major order.

In [36]:
arr.ravel()

array([26, 28, 47, 32,  5, 38, 43, 27, 12, 39, 25, 44], dtype=int32)

##### `arr.flatten()` returns a flattened copy of the NumPy array `arr`, i.e., it collapses the array into a one-dimensional array by concatenating all elements in row-major order. Unlike `ravel()`, `flatten()` always returns a copy of the array, even if it's already one-dimensional.

In [37]:
arr.flatten()

array([26, 28, 47, 32,  5, 38, 43, 27, 12, 39, 25, 44], dtype=int32)

##### `arr[-1]` accesses the last row of the NumPy array `arr`, while `arr[0]` accesses the first row. This notation allows you to slice and access specific rows within a NumPy array efficiently.

In [38]:
arr[-1]  

array([39, 25, 44], dtype=int32)

##### `arr[2:5]` retrieves rows from index 2 to index 4 (inclusive) from the NumPy array `arr`.

In [39]:
arr[2:5]

array([[43, 27, 12],
       [39, 25, 44]], dtype=int32)

##### `arr[1:]` retrieves all rows from index 1 to the end of the NumPy array `arr`.

In [40]:
arr[1:]

array([[32,  5, 38],
       [43, 27, 12],
       [39, 25, 44]], dtype=int32)

##### `arr[0:3, 0:2]` selects a sub-array from `arr` consisting of rows 0 to 2 (exclusive of 3) and columns 0 to 1 (exclusive of 2). This operation effectively creates a 2-dimensional slice of the original array.

In [41]:
arr[0:3 , 0:2]

array([[26, 28],
       [32,  5],
       [43, 27]], dtype=int32)

##### `arr[-3:, -2:]` selects a sub-array from `arr` consisting of the last 3 rows and the last 2 columns. This notation efficiently slices the array based on negative indices, which count backward from the end of the array.

In [42]:
arr[-3: , -2:]

array([[ 5, 38],
       [27, 12],
       [25, 44]], dtype=int32)

In [43]:
arr= np.random.randint(5,50,(10 , 5))   # 10 row and 5 column between 5-50
arr


array([[10, 20, 26, 47,  7],
       [27, 21,  9, 41, 22],
       [28, 24, 40, 41, 44],
       [35, 13, 13, 14, 45],
       [ 6, 40, 43, 13, 10],
       [20, 35, 31, 19, 44],
       [12, 14, 40, 12, 43],
       [ 7, 38, 46, 17, 13],
       [35, 43, 49, 23, 13],
       [31, 23, 41, 33,  8]], dtype=int32)

##### `arr[3:6, 2:5]` selects a sub-array from `arr` consisting of rows 3 to 5 (exclusive of 6) and columns 2 to 4 (exclusive of 5). This one-liner effectively retrieves a 2-dimensional slice of the original array based on specified row and column indices.

In [44]:
arr[3:6, 2:5]

array([[13, 14, 45],
       [43, 13, 10],
       [31, 19, 44]], dtype=int32)

##### arr[0::2, 2:5] selects a sub-array from arr where:
##### The rows are selected starting from index 0 and jumping 2 rows at a time (0::2).
##### The columns are selected from index 2 to 4 (exclusive of 5).
##### jump point by default 1 jumping point 2 means jump one row


In [45]:
arr[0: : 2, 2:5]   

array([[26, 47,  7],
       [40, 41, 44],
       [43, 13, 10],
       [40, 12, 43],
       [49, 23, 13]], dtype=int32)

##### `arr = np.random.randint(2, 12, (5, 10, 5))` creates a NumPy array `arr` with shape (5, 10, 5), where each element is a random integer chosen from the interval [2, 12). This array has 5 slices, each containing a 10x5 matrix of random integers.

In [46]:
arr = np.random.randint(2,12,(5,10,5))
arr

array([[[ 4, 10,  7,  7,  9],
        [ 7,  7,  6,  7,  3],
        [11,  8,  4,  6,  5],
        [ 2,  3, 11,  4,  4],
        [ 3, 11,  5,  9, 10],
        [ 6,  5,  6,  6,  9],
        [10, 11,  9,  2,  2],
        [ 7,  4, 10, 10,  5],
        [ 4,  4,  2,  2, 11],
        [ 9, 10,  5,  7,  4]],

       [[ 4, 11, 10,  4,  6],
        [ 6,  7, 10,  7,  6],
        [ 7,  8, 11,  4,  3],
        [ 5,  9,  2,  5,  2],
        [ 2,  4,  8,  2,  8],
        [ 5,  2,  3,  7,  4],
        [ 6,  8,  3,  2, 10],
        [ 7,  4,  9,  3,  3],
        [ 4,  2,  2,  9,  9],
        [ 9,  9,  5,  2,  4]],

       [[ 4,  8,  8, 11,  8],
        [ 3,  3,  4,  3,  9],
        [ 5, 11,  6,  8,  5],
        [ 7,  7,  7,  7,  4],
        [ 2,  7,  5,  6, 10],
        [11,  8, 10,  4,  9],
        [10,  7,  7,  3,  5],
        [ 6, 10, 10,  9, 11],
        [ 6,  7,  7, 10,  5],
        [ 2, 11,  2,  7,  7]],

       [[ 4,  2,  6,  6,  5],
        [ 8,  7,  8,  9,  7],
        [ 7,  8,  9,  4,  2],
    

##### arr.shape for 3D Array -----> Table-> 5, Row-> 10  , Column-> 5

In [47]:
arr.shape


(5, 10, 5)

##### 'arr[0]'   -----> return table 1

In [48]:
arr[0]  

array([[ 4, 10,  7,  7,  9],
       [ 7,  7,  6,  7,  3],
       [11,  8,  4,  6,  5],
       [ 2,  3, 11,  4,  4],
       [ 3, 11,  5,  9, 10],
       [ 6,  5,  6,  6,  9],
       [10, 11,  9,  2,  2],
       [ 7,  4, 10, 10,  5],
       [ 4,  4,  2,  2, 11],
       [ 9, 10,  5,  7,  4]], dtype=int32)

##### slicing for 3D Array
##### arr[Table slicing , Row slicing , Column slicing]

In [49]:
arr[0 , 8:10 , 2:5]  

array([[ 2,  2, 11],
       [ 5,  7,  4]], dtype=int32)

##### last row of every table

In [50]:
arr[0: , 9:10 , 0:6 ]   

array([[[ 9, 10,  5,  7,  4]],

       [[ 9,  9,  5,  2,  4]],

       [[ 2, 11,  2,  7,  7]],

       [[ 2,  2,  5,  2,  4]],

       [[ 9,  4,  6,  6,  7]]], dtype=int32)

In [51]:
arr= np.array([7,5,9])
arr

array([7, 5, 9])

##### max function return value of max item in given array

In [52]:
arr.max()   

np.int64(9)

##### argmax function return the position of maximum item

In [53]:
arr.argmax()   

np.int64(2)

##### min function return the value of minimum item in given array

In [54]:
arr.min()

np.int64(5)

##### argmin function return the position of manimum item

In [55]:
arr.argmin()    

np.int64(1)

##### arr.sort() function arranging array elements  in ascending order

In [56]:
arr.sort()
arr

array([5, 7, 9])

##### The expression arr[::-1] creates a reversed version of the list arr. 



In [57]:
arr[::-1]

array([9, 7, 5])

##### This function gives sorting index of item    0->5 ; 1->7 ; 2->9

In [58]:
arr.argsort()  

array([0, 1, 2])

 ##### arr.unique() function used for find uniqe items

In [59]:
np.unique(arr)  


array([5, 7, 9])

##### arr.var() function used for find the variance of given arr

In [60]:
arr.var()

np.float64(2.6666666666666665)